In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Connect to the database

engine = create_engine('mysql+pymysql://root:root@123@localhost/covid_exploration')

In [3]:
covid_deaths = pd.read_csv('covid-deaths.csv')
covid_deaths

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113106,ZWE,Africa,Zimbabwe,2021-08-26,15092171.0,123986.0,275.0,297.714,4356.0,18.0,...,1.496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113107,ZWE,Africa,Zimbabwe,2021-08-27,15092171.0,124236.0,250.0,333.429,4374.0,18.0,...,1.666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113108,ZWE,Africa,Zimbabwe,2021-08-28,15092171.0,124367.0,131.0,268.571,4390.0,16.0,...,1.458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113109,ZWE,Africa,Zimbabwe,2021-08-29,15092171.0,124437.0,70.0,255.000,4401.0,11.0,...,1.439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113110,ZWE,Africa,Zimbabwe,2021-08-30,15092171.0,124581.0,144.0,225.714,4416.0,15.0,...,1.164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
covid_vaccinations = pd.read_csv('covid-vaccinations.csv')
covid_vaccinations

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,2020-02-24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113106,ZWE,Africa,Zimbabwe,2021-08-26,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
113107,ZWE,Africa,Zimbabwe,2021-08-27,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
113108,ZWE,Africa,Zimbabwe,2021-08-28,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
113109,ZWE,Africa,Zimbabwe,2021-08-29,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
113110,ZWE,Africa,Zimbabwe,2021-08-30,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN

In [ ]:
# Writing the data frames to sql table

In [5]:
covid_deaths.to_sql(con=engine, name='covid_deaths', if_exists='replace', index = False)

In [6]:
covid_vaccinations.to_sql(con=engine, name= 'covid_vaccinations', if_exists= 'replace', index = False)